cu_up:
  e1ap:
    cu_cp_addr: 127.0.20.1
    bind_addr: 127.0.20.2
  ngu:
    no_core: true
    socket:
      - bind_addr: 127.0.0.1
  f1u:
    socket:
      - bind_addr: 127.0.10.1

log:
  filename: /stage/cu_up.log
  all_level: info
